const {
  VITE_API_URL = "",
  VITE_LOG_VISIT_PATH = "",
  VITE_HLS_PROXY_PATH = "",
  DEV,
  VITE_DASHBOARD_STATS_PATH = ""
} = import.meta.env;


export const ENV = {
  IS_DEV_MODE: DEV,
  API_URL: VITE_API_URL,
  LOG_VISIT_URL: VITE_API_URL + VITE_LOG_VISIT_PATH,
  HLS_PROXY_URL: VITE_API_URL + VITE_HLS_PROXY_PATH,
  DASHBOARD_STATS_PATH: VITE_API_URL + VITE_DASHBOARD_STATS_PATH
} as const;